### ISSUE TITLE
Multiple subscriber entering same time crash

### ISSUE THREAD

**Issue by alperenbabagil** [opentok/accelerator-core-android#88] opened 2019-03-21 11:29 UTC
## New issue checklist

- [x] I have read all of the [`README`](../README.md) 
- [x] I have searched [existing issues](https://github.com/opentok/accelerator-core-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.0.26
- iOS/Android/Browser version(s): 3 devices: All Android 8
- Devices/Simulators/Machine affected: Samsung A5, Huawei P9, Asus Z012D
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

#### Expected behavior

> Minimum 3 attendee can chat together

#### Actual behavior

> When 2 subscribers entering same session, publisher closes session

#### Steps to reproduce

>Open a session from publisher and attend with min 2 subscribers at the same time

#### Crash log? Screenshots? Videos? Sample project?

>... No crash log, just Session.SessionListener calls onDisconnected(SELF, 0,
                            mSessionConnection.getConnectionId(),
                            mSessionConnection.getData());

## Question or Feature Request

> ...

**Comment by igorwojda** [comment] 2020-09-14 08:29
Thx for your feedback. 
I was unable to reproduce the problem, most likely because this issue faces very old version of the SDK.
I will close it for now, but feel free to reopen it if you still think this problem exists.

**Closed by igorwojda** 2020-09-14 08:29 UTC
